---
# DESCRIPTION
# Apply APT updates
# Author: Shamelessly based on the Windows update playbook from u/zoredache on r/ansible

# Process!!
# Update the APT cache FIRST (requires sudo): ansible-playbook apply_apt_updates.yml --tags cache -K
# Perform a quick check utilizing the built in MOTD: ansible-playbook apply_apt_updates.yml --tags quick
# List available updates: ansible-playbook apple_apt_updates.yml --tags list
# Perform a check that lists the upgradable packages and if a reboot is needed: ansible-playbook apply_apt_updates.yml --tags check
# Perform any non-phased updates (requires sudo): ansible-playbook apply_apt_updates.yml --tags update -K
# Perform a check to see if file "/var/run/reboot-required" exists : ansible-playbook apply_apt_updates.yml --tags reboot-check
# Perform any needed reboots, will skip VMs that do not need it (requires sudo): ansible-playbook apply_apt_updates.yml --tags reboot -K
# To limit the playbook to any hosts or group use the -l tag -  -l 'all:!shoresy' will use all hosts except the internal lab labeled "shoresy"


- name: Apply APT Updates
  hosts: apt
  gather_facts: no

  tasks:

  - block:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags:
      - cache

    - name: Gather MOTD Package Update
      shell: bash /etc/update-motd.d/90-updates-available | grep applied
      register: motd_results
      tags:
      - check
      - quick 

    - name: Gather Upgradable Packages
      shell: apt list --upgradable 
      register: update_results
      tags:
      - check
      - list 

#    - name: Gather Phased Update
#      shell: apt list 2>/dev/null --upgradable | cut -f1 -d"/" | grep -v Listing | xargs -L1 apt policy 2>/dev/null | grep phased
#      register: phased_results
#      tags:
#      - update
#      - check

    - name: Upgrade
      ansible.builtin.apt:
        upgrade: dist  
      become: yes
      tags:
      - update

    - name: Cleanup
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
      become: yes
      tags:
      - update

    - name: Check if Reboot Required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      tags:
      - check
      - reboot-check
      - reboot

    - name: Show Upgradable Packages
      debug: msg="{{ update_results.stdout }}"
      tags:
      - check
      - list

    - name: Show MOTD
      debug: msg="{{ motd_results.stdout }} "
      tags:
      - check
      - quick

    - name: Reboot Required?
      debug: 
        msg="Reboot Required"
      when: reboot_required_file.stat.exists
      tags:
      - check
      - reboot
      - reboot-check

    - name: Reboot if Required
      reboot:
      when: reboot_required_file.stat.exists 
      become: yes
      tags:
      - reboot
