---
# DESCRIPTION
# Apply APT updates
# Author: Shamelessly based on the Windows update playbook from u/zoredache on r/ansible

# check
# ansible-playbook apply_linux_updates.yml --tags check
# install without reboot
# ansible-playbook apply_linux_updates.yml -K --tags install

- name: Apply APT Updates
  hosts: apt
  gather_facts: yes

  tasks:

  - block:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags:
      - update 

    - name: Gather Upgradable Packages
      shell: apt list --upgradable
      register: update_results
      tags:
      - update
      - check

    - name: Show Update Results
      debug: msg="{{ update_results.stdout }}"
      tags:
      - update
      - check

    - name: Upgrade Dist
      ansible.builtin.apt:
        upgrade: dist  
      become: yes
      tags:
      - update

    - name: Cleanup
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
      become: yes
      tags:
      - update

    - name: Check if Reboot Required
      stat:
        path: /run/reboot-required
      register: reboot_required_file
      tags:
      - update
      - reboot

    - name: Reboot if Required
      reboot:
      when: reboot_required_file.stat.exists == true
      become: yes
      tags:
      - reboot

