---
- name: Update Everything on Linux RHEL based VMs
  hosts: leo
  become: true

  tasks:
    - name: Gather Upgradable Packages
      shell: sudo yum list updates -y
      register: result
      tags:
      - check
      - update

    - name: Show YUM Output
      debug: msg="{{ result.stdout }}"
      tags:
      - check
      - update

    - name: Upgrade
#      ansible.builtin.yum:
#        name: '*'
#        state: latest
      shell: sudo yum update -y
      tags:
      - update

    - name: Cleanup 
#      ansible.builtin.yum:
#        autoremove: yes
      shell: sudo yum clean all
      tags:
      - update

    - name: Check if Reboot Required
      stat:
        path: /run/reboot-required
      register: reboot_required_file
      tags:
      - check
      - update
    
    - name: Reboot if Required
      reboot:
      when: reboot_required_file.stat.exists == true
      tags:
      - check
      - update
