---
# DESCRIPTION
# Apply APT updates
# Author: Shamelessly based on the Windows update playbook from u/zoredache on r/ansible

# Process
# Update the APT cache FIRST (requires sudo): ansible-playbook apply_apt_updates.yml --tags update-cache -K
# Perform a quick check utilizing the built in MOTD: ansible-playbook apply_apt_updates.yml --tags quick
# Perform a check that lists the upgradable packages (phased updated WIP): ansible-playbook apply_apt_updates.yml --tags check
# Perform any non-phased updates (requires sudo): ansible-playbook apply_apt_updates.yml --tags update -K
# Perform any needed reboots(requires sudo): ansible-playbook apply_apt_updates.yml --tags reboot -K

- name: Apply APT Updates
  hosts: apt
  gather_facts: yes

  tasks:

  - block:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags:
      - update-cache

    - name: MOTD Package Update
      shell: bash /etc/update-motd.d/90-updates-available | grep applied
      register: motd_results
      tags:
      - update
      - check
      - quick 

    - name: Show MOTD
      debug: msg="{{ motd_results.stdout }}"
      tags:
      - update
      - check
      - quick 

    - name: Gather Upgradable Packages
      shell: apt list --upgradable 
      register: update_results
      tags:
      - update
      - check

#    - name: Gather Phased Update
#      shell: apt list 2>/dev/null --upgradable | cut -f1 -d"/" | grep -v Listing | xargs -L1 apt policy 2>/dev/null | grep phased
#      register: phased_results
#      tags:
#      - update
#      - check

    - name: Show Update Results
      debug: msg="{{ update_results.stdout }}"
      tags:
      - update
      - check

    - name: Upgrade Dist
      ansible.builtin.apt:
        upgrade: dist  
      become: yes
      tags:
      - update

    - name: Cleanup
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
      become: yes
      tags:
      - update

    - name: Check if Reboot Required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      tags:
      - update
      - reboot

    - name: Reboot if Required
      reboot:
      when: reboot_required_file.stat.exists == true
      become: yes
      tags:
      - reboot

# Needs more refinement
#    - name: Gather Upgradable Packages
#      shell: apt list 2>/dev/null --upgradable | cut -f1 -d"/" | grep -v Listing
#    - name: Show Update Results
#      debug: msg="Package {{ update_results.stdout }} is {{ phased_results.stdout }}"
