---
# DESCRIPTION
# Display MOTD without sudo or tags
# Author: Shamelessly based on the Windows update playbook from u/zoredache on r/ansible

- name: Message of the Day 
  hosts: apt
  gather_facts: no

  tasks:

  - block:
    - name: Gather MOTD Package Update
      shell: bash /etc/update-motd.d/90-updates-available | grep applied
      register: motd_results

    - name: Show MOTD
      debug: msg="{{ motd_results.stdout }}"

    - name: Check if Reboot Required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Show if Reboot Required
      debug: 
        msg="Reboot Required"
      when: reboot_required_file.stat.exists
