---
# DESCRIPTION
# Author: Robert on SuperUser.com
- hosts: all 
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
    tags:
    - distro
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
    tags:
    - version
  - name: Distro Version
    debug: msg="{{ ansible_distribution  +  ansible_distribution_version }}"
    tags:
    - dversion 
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
    tags:
    - major
