---
# DESCRIPTION
# Author: Robert on SuperUser.com
- hosts: all 
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
    tags:
    - distro
  - name: Distro Version
    debug: msg="{{ ansible_distribution  +  ansible_distribution_version }}"
    tags:
    - main
