---
# DESCRIPTION
# Author: Robert on SuperUser.com
- hosts: all 
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
    tags:
    - distro
    - os
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
    tags:
    - version
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
    tags:
    - major
