---
# DESCRIPTION
# Display MOTD without sudo or tags
# Author: Shamelessly based on the Windows update playbook from u/zoredache on r/ansible

- name: Message of the Day 
  hosts: apt
  gather_facts: no

  tasks:

  - block:
    - name: Gather Landscape
      shell: bash /etc/update-motd.d/50-landscape-sysinfo
      register: landscape_results
      tags:
      - landscape

    - name: Gather Updates Package Update
      shell: bash /etc/update-motd.d/90-updates-available | grep applied
      register: update_results
      tags:
      - update

    - name: Check if Reboot Required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      tags:
      - reboot

    - name: Show Landscape
      debug: msg="{{ landscape_results.stdout }}"
      tags:
      - landscape

    - name: Show Updates
      debug: msg="{{ update_results.stdout }}"
      tags:
      - update

    - name: Show if Reboot Required
      debug: 
        msg="Reboot Required"
      when: reboot_required_file.stat.exists
      tags:
      - reboot
