---
# DESCRIPTION
# Apply APT updates
# Author: Shamelessly based on the Windows update playbook from u/zoredache on r/ansible

# Process
# Perform a check to see if file "/var/run/reboot-required" exists : ansible-playbook apply_apt_updates.yml --tags reboot-check
# Perform any needed reboots(requires sudo): ansible-playbook apply_apt_updates.yml --tags reboot -K

- name: Reboot Management
  hosts: apt
  gather_facts: no

  tasks:

  - block:
    - name: Check if Reboot Required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      tags:
      - reboot-check
      - reboot

    - name: Show if Reboot Required
      debug: 
        msg="Reboot Required"
      when: reboot_required_file.stat.exists
      tags:
      - reboot-check

    - name: Reboot if Required
      reboot:
      when: reboot_required_file.stat.exists 
      become: yes
      tags:
      - reboot
