---
- name: Update Timezone to America/Indiana/Indianapolis 
  hosts: all
  become: true

  tasks:
    - name: Update Timezone to ETC/UTC
      copy: content="Etc/UTC\n" dest=/etc/timezone owner=root group=root mode=0644
      sudo: true
      register: timezone

    - name: Reconfigure timezone Data (if changed)
      shell: dpkg-reconfigure -f noninteractice tzdata
      sudo: true
      register: timezone.changed
