---
- name: Check Twingate Status and Version
  hosts: twingate

  tasks:

    - name: Twingate Status
      ansible.builtin.systemd:
        name: twingate-connector.service
      register: tw_status
      debug:
        var: tw_status.status.ActiveState
      tags:
      - status
    - name: Twingate Version
      ansible.builtin.shell:
        cmd: twinagte-connector -V
      register: tw_version
      debug:
        var: tw_version.status.ActiveState
      tags:
      - version
