---
- name: Update Twingate-connectors
  hosts: twingate
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade Twingate-connectors
      apt:
        name: twingate-connector
        state: latest

    - name: Gather Package Facts
      package_facts:
          manager: auto


    - name: Print Package Facts
      ansible.builtin.debug:
        var: ansible_facts.packages

    - name: Check whether a package called foobar is installed
      ansible.builtin.debug:
       msg: "{{ ansible_facts.packages['twingate-connector'] | length }} versions of twingate-connector are installed!"
      when: "'twingate-connector' in ansible_facts.packages"

    - name: Twingate-Connector versions
      ansible.builtin.command: twingate-connector -V
