---
- name: Update Twingate-connectors
  hosts: twingate
  become: true

  tasks:
    - name: Update APT Cache
      apt:
        update_cache: yes

    - name: Upgrade Twingate Connectors
      apt:
        name: twingate-connector
        state: latest

    - name: Gathering Twingate-Connector Versions
      ansible.builtin.command: twingate-connector -V
      register: twingate_version
      
    - name: Printing Twingate-Connector Version
      debug: 
        msg: The current Twingate Connection version is {{ twingate_version.stdout }}