---
- name: Update Everything on Linux VMs
  hosts: linux 
  become: false
  gather_facts: false 

  tasks:
    - name: Gather Upgradable Packages
      shell: apt list --upgradable
      register: updateresult
      
    - name: Show Update Results
      debug: msg="{{ updateresult.stdout }}"
