---
- name: Update Everything on Linux
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade
      ansible.builtin.apt:
        upgrade: dist
     
    - name: Cleanup
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes