---
- name: Update Everything on Linux RHEL based VMs
  hosts: leo
  become: true

  tasks:
    - name: Update yum cache
      ansible.builtin.dnf:
        update_cache: yes

    - name: Gather Upgradable Packages
      shell: dnf check-update
      register: result

    - name: Show dnf Output
      debug: msg="{{ result.stdout }}"

    - name: Upgrade dnf
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Cleanup dnf
      ansible.builtin.dnf:
        autoremote: yes

    - name: Check if Reboot Required
      stat:
        path: /run/reboot-required
      register: reboot_required_file
    
    - name: Reboot if Required
      reboot:
      when: reboot_required_file.stat.exists == true
      
