---
  - name: Get Cluster Info
    hosts: otava 
    connection: local
    gather_facts: false
    environment:

    tasks:
    - name: Get Cluster Info
      scale_computing.hypercore.api:
        endpoint/rest/v1/Cluster/e75ff703-d1ad-41e1-8dd3-676bbbfd2bac
        action: get
      register: info

    - name: Display Info
      debug:
#        var: info.json.value
        var: info