---
- name: Update Twingate-connectors
  hosts: twingate
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade Twingate-connectors
      apt:
        name: twingate-connector
        state: latest
    
    - name: Check twingate-connector Version
      shell: twingate-connector -V
      register: CURRENT_INSTALLED_VERSION

    - debug:
        msg: "{{ CURRENT_INSTALLED_VERSION }}"
    