---
- name: Update Everything on APT based Linux VMs
  hosts: linux
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade
      ansible.builtin.apt:
        upgrade: dist
     
    - name: Cleanup
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes

    - name: Check if Reboot Required
      stat:
        path: /run/reboot-required
      register: reboot_required_file
    
    - name: Reboot if Required
      reboot:
      when: reboot_required_file.stat.exists == true
      

