---
- name: Update Everything on Linux VMs
  hosts: win

  tasks:
    - name: Install all Critical and Security Updates
      win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        state: installed
        reboot: true
      

#    - name: Reboot VM if required
#      win_reboot:
#      when: update_result.reboot_required
